"""Add is_test_order flag to orders table

Revision ID: 002_add_is_test_order
Revises: 001_initial
Create Date: 2026-01-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "002_add_is_test_order"
down_revision: Union[str, None] = "001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add is_test_order column with default False
    op.add_column(
        "orders",
        sa.Column("is_test_order", sa.Boolean(), nullable=False, server_default="false"),
    )

    # Create index for filtering test orders
    op.create_index("idx_orders_is_test_order", "orders", ["is_test_order"])

    # Update existing test orders (receipt IDs starting with 99)
    # Test orders have receipt IDs that start with 99 (generated by test_orders.py)
    op.execute(
        """
        UPDATE orders
        SET is_test_order = true
        WHERE CAST(etsy_receipt_id AS TEXT) LIKE '99%'
        """
    )


def downgrade() -> None:
    op.drop_index("idx_orders_is_test_order", table_name="orders")
    op.drop_column("orders", "is_test_order")
